pipeline {
    agent any

        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_REGION = ${region}
        S3_BUCKET = ${S3_BUCKET}
        S3_KEY = ${S3_KEY}

    stages {
        stage('Checkout') {
            steps {
                git branch: "main" , url: 'git@github.com:Zudypubg/Terraform-mock-project.git'
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh 'terraform plan '
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'terraform apply -auto-approve '
            }
        }
    }

    // post {
    //     always {
    //         sh 'terraform destroy -auto-approve'
    //     }
    // }
}
